### ISSUE TITLE
Cannot find code for Morse potential calculation

### ISSUE THREAD

**Issue by yippp** [masashitsubaki/QuantumGNN_molecules#1]
In the file `run_training.py`, I can just find a line  `potentials = torch.exp(-self.gamma[i] * distances ** 2)` related with Morse potential. But I do not think it is matched with the equations (5) - (8) in the supplementary of your paper. 
Could you give me more details about that?

**Comment by masashitsubaki** [comment]
I'm sorry that this code is a beta version and this implementation provides only Gaussian kernel-like potential transformation from the atomic distance matrix, i.e., torch.exp(-self.gamma[i] * distances ** 2), because of the simplicity.

Of course, instead of using this Gaussian-based potential, we can use Morse-based potential and its implementation is like this: D[i] * (1 - torch.exp(-a[i] * distances - r)) ** 2. I will implement this in the next commit.

But, in the last week, I found that the preprocessing is mistaken in the provided QM9 dataset in the directory of dataset/original. I'm very sorry. I will fix this in the next commit and release the major updated version of this code.
